# Copyright (c) 2019 Michael Ackermann, aggi
# high speed PRNG based upon non-primitive recurs polymorphic linear feedback shift register matrix

O_TARGET := scramdom.o

obj-y	:= scrandom.o

obj-m   := $(O_TARGET)

include $(TOPDIR)/Rules.make
